apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
      - name: web
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 5000
        env:
        - name: DB_HOST
          value: "{{ .Values.mysql.host }}"
        - name: DB_USER
          value: "{{ .Values.mysql.user }}"
        - name: DB_PASS
          value: "{{ .Values.mysql.password }}"
