apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-devops-poc
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: aws-devops-poc
  template:
    metadata:
      labels:
        app: aws-devops-poc
    spec:
      containers:
        - name: aws-devops-poc
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.containerPort }}
            initialDelaySeconds: 5
            periodSeconds: 10
