name: CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
  #  - name: Build Docker image
  #    run: docker build -t ghcr.io/${{ github.repository }}:${{ github.sha }} .

   # - name: Push to GitHub Container Registry
    #  run: |
     #   echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      #  docker push ghcr.io/${{ github.repository }}:${{ github.sha }}

   # - name: Deploy via Helm
    #  run: |
    #    helm upgrade --install myapp ./app/helm \
     #     --set image.repository=ghcr.io/${{ github.repository }} \
      #    --set image.tag=${{ github.sha }}
