name: CI/CD - Build, Push, Deploy

on:
  push:
    branches: [ demo-devops-helm ]

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
